In [5]:
import pandas as pd 

file_path = 'datasets/heart.csv'
df = pd.read_csv(file_path)

df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', 
              '심전도', '최대심박수', '운동유발협심증', 'ST우울증', '운동후ST검사', 
              '주요혈관수', '결합유형', '심장질환여부'] 

print(df)
df.head()

     나이  성별  흉통유형  안정시혈압  콜레스테롤  공복혈당  심전도  최대심박수  운동유발협심증  ST우울증  운동후ST검사  \
0    63   1     3    145    233     1    0    150        0    2.3        0
1    37   1     2    130    250     0    1    187        0    3.5        0
2    41   0     1    130    204     0    0    172        0    1.4        2
3    56   1     1    120    236     0    1    178        0    0.8        2
4    57   0     0    120    354     0    1    163        1    0.6        2
..   ..  ..   ...    ...    ...   ...  ...    ...      ...    ...      ...
298  57   0     0    140    241     0    1    123        1    0.2        1
299  45   1     3    110    264     0    1    132        0    1.2        1
300  68   1     0    144    193     1    1    141        0    3.4        1
301  57   1     0    130    131     0    1    115        1    1.2        1
302  57   0     1    130    236     0    0    174        0    0.0        1

     주요혈관수  결합유형  심장질환여부
0        0     1       1
1        0     2       1
2        0     2       1
3        0     2       1
4        0     2       1
..     ...   ...     ...
298      0     3       0
299      0     3       0
300      2     3       0
301      1     3       0
302      1     2       0

[303 rows x 14 columns]

,나이,성별,흉통유형,안정시혈압,콜레스테롤,공복혈당,심전도,최대심박수,운동유발협심증,ST우울증,운동후ST검사,주요혈관수,결합유형,심장질환여부
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1